### ISSUE TITLE
Releasing Capybara Hardware Files and TempAlarm App

### ISSUE THREAD

**Issue by adkinsjd** [CMUAbstract/releases#1]
Can you release the Capybara hardware files and the temp alarm application?

Thanks!

**Comment by blucia0a** [comment]
Yes!  We're cleaning up v2.0 and we are planning to make all the source materials and design files public very soon.

**Comment by alexeicolin** [comment]
TempAlarm is actually already public: https://github.com/CMUAbstract/app-tempalarm
The most recent branch is `capybara-v2` with changes for the latest board revision (v2.0).

**Comment by alexeicolin** [comment]
I fixed the link in the app table.
Also, for build instructions see the discussion in the Benchmark Applications section: https://github.com/CMUAbstract/releases#benchmark-applications

**Comment by adkinsjd** [comment]
Thanks for pointing me to the right spot!

**Comment by alexeicolin** [comment]
HW Design released here: https://github.com/CMUAbstract/capybara
(I'm closing, but please feel free to re-open if anything turns out inaccessible or missing.)
